//This function is responsible for constracting and adding new product to a stores collection

const db_connection = require('../Model/DB_connection');

module.exports = async function(name, category, price, productType) {

    //name of store or store id has to be generated from token in functure
    let storeName = 'courageBusiness'

    try {
        let Db = await db_connection(storeName, 'Products')
        return await Db.insertOne({
            Name: name,
            Category: category,
            Price: price,
            Stock: null,
            ProductLedger: {},
            productType: {
                sealsType: productType.sealsType,
                bulkNumber: productType.bulkNumber,
                Discount: productType.discount
            }
        })

    } catch (error) {
        console.log('msg:' + error)
    }
}


/** 
 * the product componet is the core piece of this system
 * the product holds the details accosiated with the store 
 * Descriptions
 * -Name : decribes the name of the product 
 * -Id : the identifier of the product is generated by mongodb uporn adding a new product 
 * -ProductType : the type of the product, if it can as a bulk and single. togeter with the discount
 *  in a set of strictly single seals
 * -Price : the price of the product
 * product ledger:
 * stock : stock of product remaining in the store
 */